# Generated by Django 2.2.2 on 2019-06-12 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0002_auto_20190612_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='cafe',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='discount',
            name='image',
            field=models.ImageField(default=1, upload_to='discounts_images'),
            preserve_default=False,
        ),
    ]
