# Generated by Django 2.2.2 on 2019-06-12 12:55

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0003_auto_20190612_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='location',
            field=models.CharField(default=1, max_length=2500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='discount',
            name='details',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
