# Generated by Django 2.2.2 on 2019-06-12 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0004_auto_20190612_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='details',
            field=models.TextField(),
        ),
    ]
