export const FETCH_DISCOUNTS_BEGIN = "FETCH_DISCOUNTS_BEGIN";
export const FETCH_DISCOUNTS_SUCCESS = "FETCH_DISCOUNTS_SUCCESS";
export const FETCH_DISCOUNTS_FAIL = "FETCH_DISCOUNTS_FAIL";
export const SELECT_FOOD_CATEGORY = "ADD_FOOD_CATEGORY";
export const SELECT_TIME_SLOT = "ADD_TIME_SLOT";
export const HANDLE_SEARCH_BUTTON_CLICK = "HANDLE_SEARCH_BUTTON_CLICK";
export const ADDED_TO_LIKES ="ADDED_TO_LIKES";
export const DELETE_FROM_LIKES="DELETE_FROM_LIKES";
export const FETCH_LIKES_SUCCESS = "FETCH_LIKES_SUCCESS";

// users

export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const GET_USER = "GET_USER";

export const GET_TIME = "GET_TIME";
export const GET_TIME_FAILURE = "GET_TIME_FAILURE";

export const GET_CATEGORY = "GET_CATEGORY";
export const GET_CATEGORY_FAILURE = "GET_CATEGORY_FAILURE";

export const GET_OVERLAY = "GET_OVERLAY";
export const GET_OVERLAY_FAILURE = "GET_OVERLAY_FAILURE";

export const GET_HEIGHT = "GET_HEIGHT";
export const GET_HEIGHT_FAILURE = "GET_HEIGHT_FAILURE";


