
export const FETCH_DISCOUNTS_BEGIN = "FETCH_DISCOUNTS_BEGIN";
export const FETCH_DISCOUNTS_SUCCESS = "FETCH_DISCOUNTS_SUCCESS";
export const FETCH_DISCOUNTS_FAIL = "FETCH_DISCOUNTS_FAIL";
export const ADD_FOOD_CATEGORY = "ADD_FOOD_CATEGORY";
export const ADD_TIME_SLOT = "ADD_TIME_SLOT";
export const HANDLE_SEARCH_BUTTON_CLICK = "HANDLE_SEARCH_BUTTON_CLICK";

    
